name: Retrieve information

on:
  push:
    branches: [ "main" ]

jobs:
  Retrival:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Retrieve secrets
      run: |
        aws secretsmanager get-secret-value --secret-id dev/ty/info --output json | jq .SecretString | sed -e 's/[\"/]//g'

    - name: Retrieve aws store variables
      run: |
        aws ssm get-parameter --name /dev/ty/guide | jq .Parameter.Value